### ISSUE TITLE
Does not work with loading lazy or with picture element

### ISSUE THREAD

**Issue by Krutsch** [WebReflection/with-preview#1]
When I use it in combination with the picture element and lazy loading, it will download the jpg and the webp and the fade in does not work.

[No-Preview](https://lazy-load-picture.netlify.app/)
[With-Preview](https://lazy-load-picture.netlify.app/with-preview.html)

**Comment by WebReflection** [comment]
none of your img tags point at a `.preview.jpg` file and the README is the smallest I could think of
https://github.com/WebReflection/with-preview#example

> **Images will drop the .preview part of the src and will fade in the non .preview version of the same image** once the document shows the preview, and after the non-preview version is loaded.

In any case, this is an `<img>` built-in extend, `<picture>` and `<source>` are different elements.

**Comment by Krutsch** [comment]
Oops, sorry about that, I am blind. 
I re-uploaded it in case that you are interested of the result.

**Comment by WebReflection** [comment]
this page doesn't use `is="with-preview"` in the `<img>` tag: https://lazy-load-picture.netlify.app/

both pages use `<picture>` with a `<source>` and the browser decides what to do.

this is an **img custom element built-in**, it's **not** a **picture** nor a **source** custom element builtin.

remove the `<source>` and see it working.
